version: '2'
services:
  stripe:
    image: jatin1008/stripe_api
    environment:
      - STRIPE_PRIVATE_KEY=sk_test_51MboKfSHMkXtDqYLEjmI4iuH9WzAOPitMB3kvqZWttELHTpv16qCLfHBW8GWDOxTyjeetFuBBvWknkzGB4ir7E2700IVq2G6vY
      - CLIENT_URL=http://localhost:3000
      - API_ADDRESS=http://127.0.0.1:5000
    ports:
      - 3001:3001
