apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: client-react
  template:
    metadata:
      labels:
        app: client-react
    spec:
      containers:
      - name: client-mp
        image: jatin1008/client-mp
        ports:
          - containerPort: 3000
        env: 
        - name: REACT_APP_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: api_url
        - name: REACT_APP_STRIPE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: stripe-configmap
              key: stripe_url
        

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client-react
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30003

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
spec:
  tls:
  - hosts:
    - book.co.in
    secretName: my-tls-secret
  rules:
  - host: book.co.in
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: client-service
            port:
              number: 3000
