apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-api
spec:
  selector:
    matchLabels:
      app: stripe-api
  template:
    metadata:
      labels:
        app: stripe-api
    spec:
      containers:
      - name: stripe-api
        image: jatin1008/stripe_api
        ports:
          - containerPort: 3001
        env: 
        - name: API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: api_url
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: client-configmap
              key: client_url
        - name: STRIPE_PRIVATE_KEY
          value: "sk_test_51MboKfSHMkXtDqYLEjmI4iuH9WzAOPitMB3kvqZWttELHTpv16qCLfHBW8GWDOxTyjeetFuBBvWknkzGB4ir7E2700IVq2G6vY"
        

---
apiVersion: v1
kind: Service
metadata:
  name: stripe-api-service
spec:
  selector:
    app: stripe-api
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001

